### PR TITLE
SilverStripe 4 compatibility

### PR DESCRIPTION
**Pull request by dhensby**
- Add namespace
- Update composer dependencies
- Import correct FQCNs

You'd probably want to branch existing `master` into a `1` so that you can provide support for `1.x` whilst supporting `2.x` in the `master` branch

---

todo:

- [ ] Make CMS grid field icon more like core gridfield icons

### CODE REVIEW

**Comment by dhensby** [comment]
@unisolutions do you have any desire to get this over the line?

**Comment by dhensby** [comment]
cc @uniun

**Comment by dhensby** [comment]
bump

**Comment by brew-jay** [comment]
+1 to get this merged in please.

**Comment by dhensby** [comment]
@brew-jay it'd be nice to get this in, but I haven't heard anything on this for almost half a year - I may have to run a fork

**Comment by dhensby** [comment]
In fact the last commit to master was 2016 and the last tag in 2015... so I don't hold much hope for this

**Comment by brew-jay** [comment]
@dhensby Yeah, shame as its one of the last few modules my projects using that's not SS 4.0. I guess a fork of this would be best...

**Comment by dhensby** [comment]
OK - I've emailed the maintainer and tried to get in touch via other channels (like the ss-users slack) and haven't heard anything so I'm going to run a fork of this module which should be able to take over... let me try it out

**Comment by dhensby** [comment]
OK - you can now do `composer require dhensby/silverstripe-copybutton:^2` and get this in

**Comment by brew-jay** [comment]
That's awesome! Thanks @dhensby!

**Pull request closed without merging**
